# Generated by Django 4.0.2 on 2023-02-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0006_cart_number_of_item_cart_total_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='number_of_item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_item_price',
        ),
    ]
