# Generated by Django 4.0.2 on 2023-02-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_checkoutorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutorder',
            old_name='number_of_item',
            new_name='number_of_items',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='image',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='user',
        ),
    ]
