# Generated by Django 4.0.2 on 2023-02-26 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_app', '0009_rename_number_of_item_checkoutorder_number_of_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkoutorder',
            name='total_item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
