# Generated by Django 4.0.2 on 2023-02-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_checkoutorder_name_checkoutorder_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkoutorder',
            options={'ordering': ['-id']},
        ),
    ]
