# Generated by Django 4.0.2 on 2023-03-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_remove_checkoutorder_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
    ]
